apiVersion: v1
kind: Secret
metadata:
    name: ghtoken
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:TRbmo2JOKdWCVozcWvtHIcx2+dYzUTKPkM+w1KN2kBd+K22vlWDqHw==,iv:AE6Y9GVDHtB+te5NTBXWlBXTlqAxce+fin1jOsydcdM=,tag:h6Bei6dP6S2TGO02A7kISQ==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdDAzWjNyMjNaZXhqbmRS
            TGJXemE5b0RuZDc0ZU0yODdMT0VKb0xwWXlJClFMNktWT2tTVFdET3czeTdyWGk3
            SDVsMVVseUN3aFFrQ3BQVm9hMjNlUzAKLS0tIDVyYVJUQTA4ejQ3ekZVRzVuYnpT
            N3Z6SEVTV1Uzbi9MVmxpMDVucEdEeVUKFamKbiRhYGSGDjg+ZgHszAuD8YBb3WWG
            KhwqqPjAYsv77xFVuq3apgI60QRRqAvwcbAGO2a29yB9kTanakFuWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:55:15Z"
    mac: ENC[AES256_GCM,data:2Ev+NKc3th6G0eWaufk/uMWRUbH8E/8ZLMd02Jb2i7foS/h6+l1jQihDAjQxho/cJHUhb/iwXPJSrVsF9kQDNo7OSNSP2tlp4YFd88sUwvjIO+x9NMvnVMvR17o1FNwmPeSzTVpFm9DSve7uSQh57R9qsVOs56dJHofIQAm1V5k=,iv:K1t1wtHfcD/L5wpJxhphVL87kAbpil3l1yNHYVdb4dY=,tag:1/GQlMfY6eqSjmPuo/6GAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
