apiVersion: v1
kind: Secret
metadata:
    name: ghtoken
    namespace: observability
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:GSIPZFhhJCUIhTvEBFSruxL5S94HY8GAiVFkwrXErMyw7SeFFRV6Vw==,iv:hI0H1F/u+3Dj4xR7JqnQ3x4Iow18JeVECI/gpZF/Dcs=,tag:Tru+/BRLafjDbpy75b7KVA==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdU12d3lvYmQ2ZU9VbDFa
            WXZLLzM2blRZSXNiaDJEVXNwV29KYVNwRDFvCndqaFNkZTRyVzZrWWN3eDBiM2ls
            Z3IwZzlMWUlBc0xVdEtHSzQwUkp1bG8KLS0tIEdPSDM4SmMvZUxpMTBBZndGdWFF
            T0NJYnJseTJSdUxESk1qd2NYTlJiVkkKnLLW/4YGQH880BeYhWauTDdTZe3K8aES
            RvelgGIElWQXdoDbIU+COEChy/KAckx+6TWsy5vbBMKrAUDTpx41xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:37:12Z"
    mac: ENC[AES256_GCM,data:7EtTHGbFfJD5sBCOk0LcdEGIsvkttyExI4OTLAqeHUCbAMfOBMtvtzQ0/yRKfRgIqC60BsUaz2XPQwKlM2zcksGobPrVNPnaGVuW4yL+uCEHef5dAiHzWWX5hpJRvM1OlgjjmG9C427FGWsPoQ5Ts35xf0iJiHbywe6sjlZ1GH4=,iv:ObZpy2T4+05XSoDNEynFPohBmNUHBdf9WeAY/CphU8w=,tag:HkRStVm7IyS+mmDAKklu/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
