---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: observability
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`grafana.demo.demo.traefiklabs.tech`)
      services:
        - name: grafana
          port: 3000
          namespace: observability
