apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ingress.yaml
  - namespace.yaml
  - prometheus-stack
  - jaeger
  - loki
  - promtail
  - gh-secret.yaml
