apiVersion: v1
kind: Secret
metadata:
    name: dnsapikey
    namespace: traefik
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: ENC[AES256_GCM,data:eq0kGOB29jfvWlRxVqRaPce2ts7NGWSA,iv:WS07bjWv8DLYR6Vz5y7KDagUVZF1fy1o3eBFtBeyAfQ=,tag:uiIS/XH+4nVDMJEmv/IbOQ==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOXpBRGphcG9JK3B6TXlS
            Mll6WDNLN2tsNmZteXcwcnFOc2J5cWF6bWtRCm5pUnRmSDRnQUp4bHdsTlFPNG94
            ZWxYanVMTDFoQUlUMlNhM1pHbFVuZE0KLS0tIFVoTng3OEFjU3Ezdk9UbTFqR25G
            L09tTTlqSndKaDR0N3M2VkJhREt3cjAKAYGp3LKPTZXTOTtbCMXyH0Qum2YsTreq
            onTmh+6eJNViqZwqnzyII826Pdoy9i8NXIPTVCVwblxOg/xktU9fbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:37:12Z"
    mac: ENC[AES256_GCM,data:rNRRCG6nNoPUaXr1nwCNq04D3BedHJ6UiS8skce2tfa74Sob9jYXoe1sEeWVe6WPFBtfdYiElfQhPxkFdwN+GHC21Rllk+c43ci4a6TE6CkeLBYeOuNU/oH3ThEAv1lym3UeFz9YxFKZpZuUp2enWY4pozoTnHkob+tFCvyT2gU=,iv:TBSbtkDBJYGukzYnLkh7+yzqXP3CrGCki+ksP59tzBk=,tag:eGWuawE77y15lvPhPcRRMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
