apiVersion: v1
kind: Secret
metadata:
    name: dnsapikey
    namespace: traefik
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: ENC[AES256_GCM,data:5NeAPc5QzCFrEE3wyPTQZ2bGP1FTwJV7,iv:IZYDPPeFW3pE5oJLT4AuscHliJE20KP6eTf32EHjZmQ=,tag:U/VwA0zeCbt0HgqI/tXehA==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySjIyTmY5dlpkd1RxQ2pt
            aGd0SmtibnkzVWMwUFdqeGxEQVd2cGw1QUhvCjVwY3c1Q3FLWlJBZTladWtvTDVU
            bXpXWFJ5cWM0N2Z0b0ZKUVdIQS85Q1kKLS0tIElvQnZTMUtQdUhSem1VSzU0cWJR
            ZjY1R2dIL2IzMFE3dVJBMFlFVCsyR0EKEaCeJB0p14KYRu39uKVVecroymX4Li3r
            G1NgxIEZNxQfigEqTfTQuwmww+TEke7pd27tNseKd+zY/ahzJLA0RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T09:51:17Z"
    mac: ENC[AES256_GCM,data:Iumfm17N3Gx+bhG39kW6+th8qVDeazmpIEayS+YyuCGrOncLcxWA/C3QlC0I27MyTWluNIb2Z+ZIvJdnhIdOKJjFS4UM6/uyY5miYUwT+UpeKKZrCth8oZG8w0Fuhmk0s/8sVMTK0ams7OBGqcQ1bGGNaM31Hs1iZW8Axib81KY=,iv:cNfwoXw9nCua7X5nlR7CRV1qmpCEoN7ZwIGs/EVYpNI=,tag:XRvskbQ6dDvm8Qg4q1k+1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
