apiVersion: v1
kind: Secret
metadata:
    name: hub-license
    namespace: traefik
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: null
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWaUszVmpnbmxGdjZkQUVr
            M0xMTlFtR0Z2YkVEZWNlRnpNVGN0b1BoTnlvCm9SbmtHaU15aTExR0VPMHVsdElU
            akRrT2ViQUUrRWZoakVHeUliRGNMVW8KLS0tIEJ4YXVtWWRwaXJwRWxGeFAzRytC
            aG9UdFozVXVkdmJZVTJveTd0TVJXRk0K/pkj+V8XoPR5mTty3Iel2GHZ/xIVmZdU
            o+eyqr4uQSS9qdKDwSPTv+MpZz/E6Ag6lPEJ3UnG4QhOli+a6/A5Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:37:12Z"
    mac: ENC[AES256_GCM,data:ml+Yg8Vwwrp20G6zAYGQdxTXe+TZTlnUIbOdwUUmLtQ1dFxLubPgGQBbrkRk/upPBbg8TXXmJBjS24mMEpq9U/D0vMThqRhwShkLY82aJaGIEx7MJHfhT3AEcumMK82ANCfMU46/cXe16BrzaxtIjpZ0cBp6qk6fwqVV0oTXNNc=,iv:Jr3KOuTsW+u6QFiutjFXZJygj6CM9U0lIwjGKAARa2Q=,tag:24ZxNUBEMq2lUa76CcPslA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
