apiVersion: v1
kind: Secret
metadata:
    name: hub-license
    namespace: traefik
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token: ENC[AES256_GCM,data:yjFpv5eY7h1r+ffFeWJjVn86TjVOzoWauQFSOFJZtNAHBrsl1V4pUegF2WwUhzCO3d9+VzZdkDQrvOQQaTY1++zntEWMgqfKeB8/q35kldT/QrIYNvx1VsPGGdcv6HfYQ8cdihHLIqbaDBkLqwvUCw4O0iOI+CPk1F59YmFG66mTqTYZ9pa1E04NUNyMCJWamxh1X8Vxo0oeTZkljkP6CejVkhl8XSZbzw/uOK0VrNWZ+z0NexZ0zsGX0Ma/q1vHtTYIsZV9doTCDuuRWA4FL9vGTsF7xu7I9sBlrjZHP+sgfXe13K18MMfvveu9EcNmEvAkpYpzq3qCZjy3CaZt2dnOOM37KZJf1n7J+ncCXEWNjX0sml23RVX786YCxx2pjHj6mj9llEzheReUN+0Uj5I3TkdZGZnPbK3d+2IbGiZbN/YpJFu3e+pI/qD2Nt7jMbP9CRbVoMIr0oeOEHUr9fKLQNoKZEsakj01+V3Mw1BNMDm/Uu83weaXot4Y2Zvc/aSa5mNlgUo4jQfJggfN6i2whC9VEEbocZAirgmv1Iy8gKiovGcw4lUpS9vOMsqEHdZt4p8VXf8jWBOwAimYJ24XyUFJsqCTlsr8VPjP4GkujgEl/K4+pUc9vtdAtf3gc9WKl9VVNTMVGFIjwWZHJ8smKvLeUjg2YnYsSZ6Q0M0i7n77mMrNjFd6TjctDrKou+y9fjjOwlGyiNm6iuwdyOY4TZXmoOCtYkNWixXLjKAfTj8xF3+peU7St7gIuQrO/uKnjYrLbhcwWwjH7x5yXBwrFSt1W1rG4BrSOZYiG51ByAma3cwksMzxMgK6HQu+Wx8VEpWay+AZ/Y9gc97jgqaKRUfiXezLDCMePE2+TjKTUNvhC5lz/9dp9Yk/VFCFk0XHWO0In8pMz4FQO+C7VnDFRkcmUyK5fzYrOy1UaHTOn8kzLT8bWrWfqm3zDVE6cFufxM4HiGfcFknOZpABhdSJiFMYzOOm6hOVpqHI6EW3cPHbdvXlGJIJFG5vkL16cHrvybR6sIEj9UdEtV56JDYI5PMsjv0F+RhOtgB5YZPSqtCUyjN9ooYR5pFbbDbshHelyyp7q4TMSb1m1JapiI2TUgU6ClECVaBJyBHYZHfo9wCFO7Bo3VRkbIN3Kl5C41NlNN1DUrL4KyVWPyrEm2+svGN0ukoLrIIa58F6pxXIxlsVA6E6OjvMkQoh8rG9Bt853ly0EmepHbMFNsbeSBFHBY6JgAmG98/HWf5pobROfRuHDxsP8TXvqe/vekhl/b5d+rQS/aJtzUdCslG0Uk+F5/2mx8EjFR3cXkbOgr7KuSrdKqb15bJvLBHwDIoLTwO4DkUGnGETZe5ABg==,iv:0Fr3lBPkw01vSdcc5yYbFqpXPotQVt5XAfOIL0G4SnU=,tag:zBv410/E5+7u4A9Lfq2sgw==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQnNRN1BKSWdxTHdFaS9a
            aFhKK0h5blQvUkFwS1ZZTUdQSE15WGZxNWprClF2MkVvTDVzWHArR29OenlscmJs
            Vy9VSUpxbGxsUDJwdGVqR3A0cEVWMGsKLS0tIEVpK1E4anJkQWZaSHN3VFl4Vlhq
            dE9iQ004M0FMd0RGalZTWit4ZjFUanMKL7Qw/OdoEqCGdsTzkGhKssCqwm42KK01
            OVchyiWAdCnnsRYZyIBQxntkH7mnligkeq+ZViEpTnRQ5z4ort9GFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:55:05Z"
    mac: ENC[AES256_GCM,data:e1gMvM8vBtTHEhiGEivus3C6VVwMcP6mhE7TlnCtU8KTUG3kJT2VXEAw1hdk25U34ET9wrEA2d/8R8QJo3ui2p9fCPMkh1e7e2yfPsQIJPPzo6ab3uTXC5sfceGRWg2FcDCfzOZL+5/j3a/DVt3d4eD6nrboH+C9nKmO1ru0Wu4=,iv:f5Qdnk/kulSmZ84QB1eQYbEWWfVsuns1TZ0Rrep6+1Y=,tag:QyNbrh73678Ide+Nb4M1HA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
