apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: customers-jwt
    namespace: apps
spec:
  plugin:
    jwt:
      jwksUrl: "https://lemur-3.cloud-iam.com/auth/realms/localdemo/protocol/openid-connect/certs"
      claims: Contains(`groups`, `admin`)