{
 "title": "Traefik API demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "domain", "query": "localdemo" }
  ]
 },
 "panels": [
  {
   "title": "API total number of request over a month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"traefik/traefik\"} | json | RequestAddr=`api.$domain.demo.traefiklabs.tech` [720h]))"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum_over_time({job=\"traefik/traefik\"} | json | RequestAddr=`api.$domain.demo.traefiklabs.tech` |= \"RequestProtocol\" | json | OriginStatus=200 | unwrap DownstreamContentSize |  __error__=\"\" [$__interval])"
    }
   ]
  },
  {
   "title": "20X/30X Request per month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"traefik/traefik\"} | json | RequestAddr=`api.$domain.demo.traefiklabs.tech` | DownstreamStatus=~`[2-3][0-9][0-9]+` [720h]))"
    }
   ]
  },
  {
   "title": "40X/50X Request per month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"traefik/traefik\"} | json | RequestAddr=`api.$domain.demo.traefiklabs.tech` | DownstreamStatus=~`[4-5][0-9][0-9]+` [720h]))"
    }
   ]
  },
  {
   "title": "API logs for 20X/30X",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"traefik/traefik\"} | json | RequestAddr=\"api.$domain.demo.traefiklabs.tech\" | DownstreamStatus=~`[2-3][0-9][0-9]+`"
    }
   ]
  },
  {
   "title": "API logs for 40X/50X",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"traefik/traefik\"} | json | RequestAddr = `api.$domain.demo.traefiklabs.tech` | DownstreamStatus =~ `[4-5][0-9][0-9]+`"
    }
   ]
  },
  {
   "title": "API Access Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"traefik/traefik\"} | json | RequestAddr=\"api.$domain.demo.traefiklabs.tech\""
    }
   ]
  }
 ]
}