---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: customers-canary
  namespace: apps
spec:
  weighted:
    services:
      - name: customer-app-v2
        port: 3000
        weight: 1
      - name: customer-app-v3
        port: 3000
        weight: 0