---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: vip
  namespace: apps
spec:
  quota:
    limit: 2000
    period: 1h
  rateLimit:
    limit: 500
    period: 60s
  title: Standard plan