### observability
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
spec:
  project: default
  source:
    path: tools/overlays/observability
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Keycloak
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    path: tools/overlays/keycloak
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Apps
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    path: apps/overlays
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Traefik Dashboard
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dashboard
  namespace: argocd
spec:
  project: default
  source:
    path: ingresses/traefik-dashboard/overlays
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Traefik
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    path: traefik/overlays/hub-mgt
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Publications
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingresses
  namespace: argocd
spec:
  project: default
  source:
    path: ingresses/3-hubmgt/overlays
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
### Middlewares
---    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: middlewares
  namespace: argocd
spec:
  project: default
  source:
    path: middlewares/overlays/hub
    repoURL: https://github.com/NEwa-05/hub-demo-argocd.git
    targetRevision: localdemo
  destination:
    server: 'https://kubernetes.default.svc'
