---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.localdemo.mageekbox.eu`)
      services:
        - name: argocd-server
          port: 80
  tls: {}
