apiVersion: v1
kind: Secret
metadata:
  name: demo-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/NEwa-05/hub-demo-argocd.git
