image:
  tag: "v3.4"
deployment:
  replicas: 2
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    allowEmptyServices: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
    addInternals: true
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
metrics:
  addInternals: true
  prometheus:
    entryPoint: metrics
    addentrypointslabels: true
    addrouterslabels: true
    addserviceslabels: true
  otlp:
    enabled: true
    addentrypointslabels: true
    addrouterslabels: true
    addserviceslabels: true
    http:
      enabled: true
      endpoint: http://prometheus-stack-kube-prom-prometheus.observability.svc.cluster.local:9090/api/v1/otlp/v1/metrics
      tls:
        insecureSkipVerify: true
tracing:
  addInternals: true
  otlp:
    enabled: true
    http:
      enabled: true
      endpoint: http://simplest-collector.observability.svc.cluster.local:4318/v1/traces
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                  - traefik
          topologyKey: kubernetes.io/hostname
        weight: 100
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-mageekbox
env:
- name: POD_NAME
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
- name: GANDIV5_API_KEY
  valueFrom:
    secretKeyRef:
      name: dnsapikey
      key: token
- name: LEGO_DISABLE_CNAME_SUPPORT
  value: "true"
ports:
  websecure:
    tls:
      enabled: true
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 50m
experimental:
  plugins:
    treblle:
      moduleName: github.com/Treblle/TreblleTraefikPluginGo
      version: v1.0.5
