apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

helmCharts:
  - name: promtail
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
    releaseName: promtail
    namespace: observability
    valuesFile: values.yaml