---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`keycloak.localdemo.mageekbox.eu`)
      services:
        - name: keycloak
          port: 80
          namespace: keycloak
  tls: {}
