apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/keycloak

generators:
  - secret-generator.yaml

patches:
  - path: ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - behavior: create
    files:
      - realm.json=data/realm.json
    name: keycloak-traefik-realm
    namespace: keycloak

helmCharts:
  - name: keycloak
    includeCRDs: true
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: keycloak
    version: 21.7.1
    namespace: keycloak
    valuesFile: values.yaml
