apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: keycloak-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../base/keycloak/keycloak-secret.yaml
