apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/observability

generators:
  - secret-generator.yaml

helmCharts:
  - name: kube-prometheus-stack
    includeCRDs: true
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-stack
    namespace: observability
    valuesFile: prometheus-stack/values.yaml

patches:
  - path: ingress.yaml

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - behavior: create
    files:
      - api_demo.json=prometheus-stack/grafana-dashboards/apig/api_demo.json
    name: grafana-gateway-dashboard
    namespace: observability
