apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: observability-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../base/observability/gh-secret.yaml