---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`keycloak.demo.demo.traefiklabs.tech`)
      services:
        - name: keycloak
          port: 80
