apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    password: ENC[AES256_GCM,data:2gp2aXmpsozMYf+jbF65VToY7f5BYzYroZirCVBsG/A=,iv:kWJf817dcxEfjiVliuU1KTZYUKv0xlKD9ssFj1N5R1Y=,tag:dC9qKu7OjrjA3plzBGO/tw==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RzNIMERxUDBXR3E5dXkw
            ZUt2MmlYazZ3b0VtWXFLL0tsZ25aQURNbG04ClZ2aHhQS3ZROFA3d1Vzc0h3eElu
            ZnVMVlhFOGdMeXRTTURLVHA3a2tMS3MKLS0tIERHaEJFRkIrWnVVQ1JKdk9HRFlQ
            Q1lYQ3J5UkxWYlphY2pNZXQ3VzV6ZzQKyhCO6zMYspB3JxmqLmqHp68KPNJ2zeGc
            vENDi3noZehenv91oxIoQja8l5TN3fWJd7XV5yeKzvpWMQSgRjzMUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:37:12Z"
    mac: ENC[AES256_GCM,data:ZubYQHRiHRojCcJ/AOmTIv62DZdA1tSoMCRKJ+XanUZImGn4HtCr5YSkN4KNCyTramI7tGk4Xp79j2KOiV/C9jNzWltQWVQKtkylUdM7+uV6IK1IAAIhOT2xH1QqoTk6C3XkM6L8RZM2/mbV6Cgk9BOPlOKjMgDMAoOjFzXqvc8=,iv:1mgUK8X7BYWz7JaQOOYFaG4HOfC4S7oaSB0eibG0b3U=,tag:+gVzUf5tlnu4GbabXYog6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
