apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    password: ENC[AES256_GCM,data:Y/E2xvp8/gVORTNuBn43Oyr0wZGIkpr5yoYbRDg6Lwc=,iv:Z+dTUzBMQQmzBN5sGM6OCqmVTcopLveD5QDRunSdbzk=,tag:WBKrdn3NgJHEE9otEKxoIA==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUG5iV3AzV3ZvOWMyRVF5
            dHQ5OW9uRjdGMWt2emdRZ0JuK0pQdkdhQ1g0Ck1ZSmVjcExUeFFYVzdlalRRRXFW
            K2FHTTVoVFViaWtyMlNZSFRwUUs4bXcKLS0tIHhBVWNmSk1IZVZYdjllV1F0MzZp
            TjFaZ2FxdlkwOGJaN1ZacU9vbkt6ekUKWEgLGZzRp8xETf7HYaYt8SiOefK6lW5x
            i/FTkFe+KLNvQEseN4vD7cOc7bHDr8S2YmyODcZMFx4Xd3TxKcaB2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T09:51:17Z"
    mac: ENC[AES256_GCM,data:RdIMBtEUOIXzHWcqk7ysReeD2qzvdWIic8fTZJqC7oiGyTBzD0k6QURs2aWUTdEEDADxBXtfMsvlXM+ihdjCugRjslUCSKMp4tkpqG9AvPsLDivW13NjuRNcwYw7Bq38q7rZ6C3urMTUIxvSzLBKD1hchT2YwWic87w3ZNHGPew=,iv:abf1lpweUCouwT/lwQq0dpfDgDfKobYmgMu0PPKTuCM=,tag:NKPX0wGMCJ22P1xy8uujoQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
