apiVersion: v1
kind: Secret
metadata:
    name: keycloak-admin
    namespace: keycloak
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    password: "${KEYCLOAK_PASSWORD}"
