apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

patches:
  - path: apis/customers/api-v1.yaml
  - path: bundles/internal/bundle.yaml
  - path: catalogs/external-graphql/catalog.yaml
  - path: catalogs/internal-apis/catalog.yaml
  - path: ingresses/customers/api-ingress.yaml
  - path: ingresses/customers/api-ingress-v2.yaml
  - path: ingresses/customers/api-ingress-v3.yaml
  - path: ingresses/employees/api-ingress.yaml
  - path: ingresses/external-graphql/api-ingress.yaml
  - path: ingresses/whoami/ingress.yaml
  - path: managed-subscriptions/external-graphql/managed-susbscription.yaml
  - path: plans/std-plan.yaml
  - path: plans/vip-plan.yaml
  - path: portals/portal-ingress.yaml
  - path: portals/portal.yaml