apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

generators:
  - secret-generator.yaml

helmCharts:
  - name: traefik
    includeCRDs: true
    repo: https://traefik.github.io/charts
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
