apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: traefik-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ../../base/dns-secret.yaml
  - ../../base/hub-secret.yaml
  - ../../base/wildcard-cert.yaml