grafana:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  defaultDashboardsEnabled: false
  sidecar:
    datasources:
      alertmanager:
        enabled: false
  plugins:
    - grafana-github-datasource
  envFromSecret: ghtoken
  additionalDataSources:
    - name: Loki
      access: proxy
      isDefault: false
      editable: true
      orgId: 1
      type: loki
      url: http://loki:3100
      version: 1
    - name: github
      type: grafana-github-datasource
      isDefault: false
      secureJsonData:
        accessToken: ${GH_TOKEN}
    - name: jaeger
      access: proxy
      isDefault: false
      editable: true
      orgId: 1
      type: jaeger
      url: http://simplest-query:16686
      version: 1
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: observability
      folder: /var/lib/grafana/dashboards
      updateIntervalSeconds: 10
      resourceName: configmap/grafana-apim-dashboards,configmap/grafana-gateway-dashboard,configmap/grafana-traefik-dashboard
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
    alerts:
      enabled: false
  adminPassword: traefikhub
prometheus:
  global:
    scrape_interval: 10s
    scrape_timeout: 10s
    evaluation_interval: 10s
  prometheusSpec:
    resources:
      requests:
        memory: 512Mi
        cpu: 400m
      limits:
        memory: 512Mi
        cpu: 400m
    additionalArgs:
      - name: web.enable-otlp-receiver
        value: ""
    additionalScrapeConfigs:
      - job_name: 'traefik'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - traefik
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - source_labels: [__meta_kubernetes_pod_label_version]
          action: replace
          replacement: $1
          target_label: version
prometheus-node-exporter:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheusOperator:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m      