---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPortal
metadata:
  name: portal
  namespace: apps
spec:
  title: API Portal
  description: "Developer Portal"
  trustedUrls:
    - https://portal.${CLUSTERNAME}.${DOMAINNAME}/
  ui:
    logoUrl: https://traefik.io/favicon.png