apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traffic
resources:
  - namespace.yaml
  - traffic-user.yaml
  - traffic-user2.yaml
  - user-token-secret.yaml

generators:
  - secret-generator.yaml

configMapGenerator:
  - behavior: create
    files:
      - traffic.sh=./scripts/traffic.sh
    name: traffic-data
    namespace: traffic
