apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: traffic-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./user-token-secret.yaml