apiVersion: v1
kind: Secret
metadata:
    name: test-user-token
    namespace: traffic
stringData:
    token1: ENC[AES256_GCM,data:zRvlNVK359zkEyMqEZxF7A19hFcyXM4ucPPXZPgg3f4aMr/q3pV8tA==,iv:T0XnKdJY0QG2hYH5iYaOrgDN2rXHGPqFZgGfGxfgYcs=,tag:euOAkHQ3l/V6HSKsV+pE4A==,type:str]
    token2: ENC[AES256_GCM,data:eSxC9d81JLbhckEOSlP/ivOjGvVpOu/176RjqvVdDCLBncnaNkQyJA==,iv:m0BQ/dMxuSoQyB/kx8QwmYURq9uzb8VWoyO4nQ0O700=,tag:yb9FkhOncNx4Q+nWOjZN/g==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcld6NDVIcGMzN3B2WVZC
            cTg4TUFGN3kyUWs2bkQ0TjFxaks4Q3AxK1Q4ClRBY01VMmdqejJJcHlxWlJYcUNC
            c3o2bXNWRWR1WlcwZUFEcTc5MHVtRzQKLS0tIEhDR3ZFRE9IeHpsSURmOW93eUxB
            WmJka2hsYm9oRW4rUE9zd0U0Q1BTS28KuxCs3AVwBDy1owN85MbbXmQ2Jv3qpCLI
            O/HScmr1rgYjhg9/A7ebyoEo+bKY0B3jEUsKP50tpuGRjsrL7YHuqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T12:43:54Z"
    mac: ENC[AES256_GCM,data:BNPhBSvugW5X3kBXlm4NdnpL4iiJvLzWLoAbYcl35bQt0K+/KwkDwcsmgYfW11ngcwO8ipDyInm/G/Kre1K1N8Qvft7EBMR8G819uxtxgzETSe8r/kuxie2YW3Ol8UklqJIBhwnmOy+jCRu3IvGptbrI76iUn+del+bgm5rzth4=,iv:Sdfol4SBSq6QA2QCQSP7XQrlIjd2Uo7VAk2mylTh158=,tag:gmemS+lt5Orzhyt+DEUmfA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
