apiVersion: v1
kind: Secret
metadata:
    name: test-user-token
    namespace: traffic
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token1: ENC[AES256_GCM,data:LFwFZuvmWbnpg/lDJZz5BcFEa7jByrBGeRLwJILOwndyv3uIcSd5+g==,iv:ZP0uTXlyAgePDf4uuN2dB+MaWpQzGhWednq4uUKcwSs=,tag:PuglVLSNCDaF1OSQHZLFEw==,type:str]
    token2: ENC[AES256_GCM,data:RDIurm/8bHJmJStnrnzW/09SZS5Su8adApVb1ewfv6rwjHJEZdDDcQ==,iv:ruKFzR6chXKX4OEGIx7AuGNO7QNnhr7e7ZuNWo4ZR9Q=,tag:GEvKjjWMjtVcbpg4hdxBtg==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVkNSdXFYVSsrd05JNTgy
            Q3Y2SmQ3cytBTWlvK0M2VWtDdHpnbmJpUkFRClREdWo4aDdkMWp5MlRhc3lVeXZP
            MzhkYU1Hck5vMkVTUzJzS2l2QVl1elEKLS0tIDFhV2RpU1lSNUFncVQwU3d0L0lv
            aEtYYmtlSUl2eFlsNENvdjE3ZjhZWmsKzSxjRJLGHpH5IrT4a55AomCqcZytduLS
            FfgwMRQITUCCp5JfyUPCJsTF3u2N/s4gzzrQRdLfCV2DGcJI4IZ6vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-08T09:51:17Z"
    mac: ENC[AES256_GCM,data:+8UWoinu+yYzQddwKI8xoW6Ju5WA4zygtqTLwIlsvDbFwJvjzzw/dEnGauluKPyuyUPRwGi83AOjc3VD3Wo50AMmhkA/DrvMKtSom5VIXdmfOUt1Pd1A39kKa/VwBNJFDCwGRactJVNP3QIZGvrzo4TggLvhEshPtqQzZEJJreM=,iv:MnZnsG+dLXx+7ck/PxfQRNkJzPZkCdX4tTDOXDiiQJI=,tag:Qplvr05Ua4Rv7YEdr7c7fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
