apiVersion: v1
kind: Secret
metadata:
    name: test-user-token
    namespace: traffic
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token1: ENC[AES256_GCM,data:l0ojLuN96S6Nu2Srj1tv+Xhr+L8aAB6GPol639OBB9k3eyTi79iLRQ==,iv:NkXMXkQkRgqHPT8lTSC+Iqj6ddsjbTfhI1PlqHpcqxo=,tag:lkMgSUABVrHQANJee74YXg==,type:str]
    token2: ENC[AES256_GCM,data:i03TD4xS8mEuuSC8G6L3uU4i87GAgXhNLwnSMRl7+8AeuiojJsAJJA==,iv:nBSlJ1mbuEp6pN7App23iqZqkXTZE86NW8JGOe54zvg=,tag:5EwfNH/HRuav/Hur+9kaRQ==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza0NsNXJqQVV1aitvM1l3
            V21ON1dvYng1aENMcFVwa2VTdkZudmwrNm4wCjdDb295Ym5aQll0TVYweFpvczVG
            N2hBWmRlcGg2TlJvU0FLckFFeks5bDQKLS0tIERLd0RWNEorSmZMN2hKMTdDdndH
            aldIVWhwQkVUYndnMnYxaTZwWW9aNTAK8kTQYmmJ0G5U0nAHK/TJnpeftvRFzbE7
            GEqbS8Ufh7q9nGxvqmIGAw93ltHc6DLf8MM5VtMzySjlhNVHgyrdGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T12:50:07Z"
    mac: ENC[AES256_GCM,data:Yj6XtORqnpP7K7oluIENsybkXeITlSE7CgjFud+JU9Eflz8mVGA8rSV7TfcFEfSqxNq1oW4DqkBLuXkQ+7pllqpkeCoRKzCcBpZ0QV3GAd2JaMHfEqNCXfmJxvZVysizrVqoto87v5QYM30U1FR7nUSlLN30ID6HHgeR9Nh56Nk=,iv:doQTFiN48hWgKKaepBv57bQN5Eqm8SbIVVug43C9R3I=,tag:E/opsjDMZSN5QORL6mz7wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
