apiVersion: v1
kind: Secret
metadata:
    name: test-user-token
    namespace: traffic
stringData:
    token1: ENC[AES256_GCM,data:cT08nCehwujhlXG1AZxyIJsZSZTbW+3okzlIsvtfpJcCZyqvSQg1tw==,iv:i9CHwDvkBW/4kSsAnxi2Svjr2Ne+vP/oYYafn0YMQYQ=,tag:oUI9FXmGdxtk1niRUVGpWg==,type:str]
    token2: ENC[AES256_GCM,data:nhLGsj33b1sBW/zPbD0ZBBXLPaaOvQDmnzQrDbjsvCkmVy+xmfktvw==,iv:QeetkxiRRRmcO6Gct05928zriv7f9fseRlHniCy9fog=,tag:Pki8Wy6frEqLrMHPWN5KZw==,type:str]
sops:
    age:
        - recipient: age1j0047j4x034f7wy83y0k8cree65qpeghj3xscq0gg20ycn5a3yuqdkkqym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcFYzcnppT0tOZVV3NGVz
            SFlhQVB0TmZOcldmb3Y2TWFwK0FkUDhLOENVCk5NRmR1cDhyV1JKVFZMa2Z2T0JE
            VVpXSTNwd3N6MGJtWGc2NGFpV1h6N1kKLS0tIGVCQkFqRmVmTzVzVWJqVm9tb3V6
            NWZ4Z3pKQ25wU1RkcGsvNFpaclVGREkKL71y24t2lmvAhYWWu+U1cUb9y9AwkD8b
            BLbYexm3QaDQoavAYiJ+GEWdfanPZOPUgCRJ8vE53TOyiRqzTYFHrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T09:37:12Z"
    mac: ENC[AES256_GCM,data:L4AqzC/Wjwtbn6firoG0ngLiSCqvv/sKOQ2Hc+fArQgJoZvGFm1cgIiNbSmyWQsABW3Takk/exkSsdlW3XDlzS3F5CV2j0vHlW06sp1Nj+1fzg4JmoDumIub+oTdlEic++l+IOqQUGOZ3Nxyxv75QlQfDen2tYeHxrX0aTHZNTE=,iv:ph7QlNnmXmoB03OOkPe6ser1Z1my/yzV+wEd7cEgKa8=,tag:pliFUFM/NcJklandqH8OWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
