apiVersion: v1
kind: Secret
metadata:
    name: test-user-token
    namespace: traffic
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    token1: ${USER_TOKEN}
    token2: ${USER2_TOKEN}
