apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

helmCharts:
  - name: loki
    includeCRDs: true
    repo: https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: observability
    valuesFile: values.yaml
