apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/proxy

patches:
  - path: cors-middleware.yaml
  - path: customers-basic-auth.yaml
  - path: headers-middleware.yaml
  - path: rl-employee-middleware.yaml
  - path: rl-external-middleware.yaml
  - path: strip-middleware.yaml
  - path: whoami-basic-auth.yaml