---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: customers-apikey
  namespace: apps
spec:
  plugin:
    apiKey:
      secretNonBase64Encoded: true
      secretValues:
        - urn:k8s:secret:customers-apikey:mykey
      keySource:
        header: x-api-key
