---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: graphql-cors
  namespace: apps  
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
      - CONNECT
      - OPTIONS
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 0
    accessControlAllowHeaders: 
      - "*"